[project]
name = "tres"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.1",
    "dotenv>=0.9.9",
    "py-cord>=2.6.1",
]
