from .abc import Snowflake
from .asset import AssetMixin
from .guild import Guild
from .partial_emoji import _EmojiTag
from .role import Role
from .state import ConnectionState
from .types.emoji import Emoji as EmojiPayload
from datetime import datetime
from typing import Any, Iterator

__all__ = ['Emoji']

class Emoji(_EmojiTag, AssetMixin):
    guild_id: int
    def __init__(self, *, guild: Guild, state: ConnectionState, data: EmojiPayload) -> None: ...
    def __iter__(self) -> Iterator[tuple[str, Any]]: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def url(self) -> str: ...
    @property
    def roles(self) -> list[Role]: ...
    @property
    def guild(self) -> Guild: ...
    def is_usable(self) -> bool: ...
    async def delete(self, *, reason: str | None = None) -> None: ...
    async def edit(self, *, name: str = ..., roles: list[Snowflake] = ..., reason: str | None = None) -> Emoji: ...
