from .channel import *
import datetime
from .abc import Snowflake, SnowflakeTime
from .asset import Asset
from .automod import AutoModAction, AutoModRule, AutoModTriggerMetadata
from .channel import CategoryChannel, ForumChannel, StageChannel, TextChannel, VoiceChannel
from .colour import Colour
from .emoji import Emoji
from .enums import AuditLogAction, AutoModEventType, AutoModTriggerType, ContentFilter, NotificationLevel, ScheduledEventPrivacyLevel, VerificationLevel, VideoQualityMode, VoiceRegion
from .file import File
from .flags import SystemChannelFlags
from .integrations import Integration
from .invite import Invite
from .iterators import AuditLogIterator, BanIterator, EntitlementIterator, MemberIterator
from .member import Member
from .mixins import Hashable
from .monetization import Entitlement
from .onboarding import Onboarding
from .permissions import PermissionOverwrite, Permissions
from .role import Role
from .scheduled_events import ScheduledEvent, ScheduledEventLocation
from .stage_instance import StageInstance
from .state import ConnectionState
from .sticker import GuildSticker
from .template import Template
from .threads import Thread
from .types.guild import Guild as GuildPayload
from .user import User
from .voice_client import VoiceClient
from .webhook import Webhook
from .welcome_screen import WelcomeScreen, WelcomeScreenChannel
from .widget import Widget
from typing import NamedTuple, Sequence, overload

__all__ = ['Guild']

VocalGuildChannel = VoiceChannel | StageChannel
GuildChannel = VoiceChannel | StageChannel | TextChannel | ForumChannel | CategoryChannel
ByCategoryItem = tuple[CategoryChannel | None, list[GuildChannel]]

class BanEntry(NamedTuple):
    reason: str | None
    user: User

class _GuildLimit(NamedTuple):
    emoji: int
    stickers: int
    bitrate: float
    filesize: int

class Guild(Hashable):
    def __init__(self, *, data: GuildPayload, state: ConnectionState) -> None: ...
    @property
    def channels(self) -> list[GuildChannel]: ...
    @property
    def threads(self) -> list[Thread]: ...
    @property
    def jump_url(self) -> str: ...
    @property
    def large(self) -> bool: ...
    @property
    def voice_channels(self) -> list[VoiceChannel]: ...
    @property
    def stage_channels(self) -> list[StageChannel]: ...
    @property
    def forum_channels(self) -> list[ForumChannel]: ...
    @property
    def me(self) -> Member: ...
    @property
    def voice_client(self) -> VoiceClient | None: ...
    @property
    def text_channels(self) -> list[TextChannel]: ...
    @property
    def categories(self) -> list[CategoryChannel]: ...
    def by_category(self) -> list[ByCategoryItem]: ...
    def get_channel_or_thread(self, channel_id: int, /) -> Thread | GuildChannel | None: ...
    def get_channel(self, channel_id: int, /) -> GuildChannel | None: ...
    def get_thread(self, thread_id: int, /) -> Thread | None: ...
    @property
    def system_channel(self) -> TextChannel | None: ...
    @property
    def system_channel_flags(self) -> SystemChannelFlags: ...
    @property
    def rules_channel(self) -> TextChannel | None: ...
    @property
    def public_updates_channel(self) -> TextChannel | None: ...
    @property
    def emoji_limit(self) -> int: ...
    @property
    def sticker_limit(self) -> int: ...
    @property
    def bitrate_limit(self) -> int: ...
    @property
    def filesize_limit(self) -> int: ...
    @property
    def members(self) -> list[Member]: ...
    def get_member(self, user_id: int, /) -> Member | None: ...
    @property
    def premium_subscribers(self) -> list[Member]: ...
    @property
    def roles(self) -> list[Role]: ...
    def get_role(self, role_id: int, /) -> Role | None: ...
    @property
    def default_role(self) -> Role: ...
    @property
    def premium_subscriber_role(self) -> Role | None: ...
    @property
    def self_role(self) -> Role | None: ...
    @property
    def stage_instances(self) -> list[StageInstance]: ...
    def get_stage_instance(self, stage_instance_id: int, /) -> StageInstance | None: ...
    @property
    def owner(self) -> Member | None: ...
    @property
    def icon(self) -> Asset | None: ...
    @property
    def banner(self) -> Asset | None: ...
    @property
    def splash(self) -> Asset | None: ...
    @property
    def discovery_splash(self) -> Asset | None: ...
    @property
    def member_count(self) -> int: ...
    @property
    def chunked(self) -> bool: ...
    @property
    def shard_id(self) -> int: ...
    @property
    def created_at(self) -> datetime.datetime: ...
    @property
    def invites_disabled(self) -> bool: ...
    def get_member_named(self, name: str, /) -> Member | None: ...
    async def create_text_channel(self, name: str, *, reason: str | None = None, category: CategoryChannel | None = None, position: int = ..., topic: str = ..., slowmode_delay: int = ..., nsfw: bool = ..., overwrites: dict[Role | Member, PermissionOverwrite] = ...) -> TextChannel: ...
    async def create_voice_channel(self, name: str, *, reason: str | None = None, category: CategoryChannel | None = None, position: int = ..., bitrate: int = ..., user_limit: int = ..., rtc_region: VoiceRegion | None = ..., video_quality_mode: VideoQualityMode = ..., overwrites: dict[Role | Member, PermissionOverwrite] = ...) -> VoiceChannel: ...
    async def create_stage_channel(self, name: str, *, topic: str, position: int = ..., overwrites: dict[Role | Member, PermissionOverwrite] = ..., category: CategoryChannel | None = None, reason: str | None = None) -> StageChannel: ...
    async def create_forum_channel(self, name: str, *, reason: str | None = None, category: CategoryChannel | None = None, position: int = ..., topic: str = ..., slowmode_delay: int = ..., nsfw: bool = ..., overwrites: dict[Role | Member, PermissionOverwrite] = ..., default_reaction_emoji: Emoji | int | str = ...) -> ForumChannel: ...
    async def create_category(self, name: str, *, overwrites: dict[Role | Member, PermissionOverwrite] = ..., reason: str | None = None, position: int = ...) -> CategoryChannel: ...
    create_category_channel = create_category
    async def leave(self) -> None: ...
    async def delete(self) -> None: ...
    async def set_mfa_required(self, required: bool, *, reason: str = None) -> None: ...
    async def edit(self, *, reason: str | None = ..., name: str = ..., description: str | None = ..., icon: bytes | None = ..., banner: bytes | None = ..., splash: bytes | None = ..., discovery_splash: bytes | None = ..., community: bool = ..., afk_channel: VoiceChannel | None = ..., owner: Snowflake = ..., afk_timeout: int = ..., default_notifications: NotificationLevel = ..., verification_level: VerificationLevel = ..., explicit_content_filter: ContentFilter = ..., system_channel: TextChannel | None = ..., system_channel_flags: SystemChannelFlags = ..., preferred_locale: str = ..., rules_channel: TextChannel | None = ..., public_updates_channel: TextChannel | None = ..., premium_progress_bar_enabled: bool = ..., disable_invites: bool = ...) -> Guild: ...
    async def fetch_channels(self) -> Sequence[GuildChannel]: ...
    async def active_threads(self) -> list[Thread]: ...
    def fetch_members(self, *, limit: int | None = 1000, after: SnowflakeTime | None = None) -> MemberIterator: ...
    async def search_members(self, query: str, *, limit: int = 1000) -> list[Member]: ...
    async def fetch_member(self, member_id: int, /) -> Member: ...
    async def fetch_ban(self, user: Snowflake) -> BanEntry: ...
    async def fetch_channel(self, channel_id: int, /) -> GuildChannel | Thread: ...
    def bans(self, limit: int | None = None, before: Snowflake | None = None, after: Snowflake | None = None) -> BanIterator: ...
    async def prune_members(self, *, days: int, compute_prune_count: bool = True, roles: list[Snowflake] = ..., reason: str | None = None) -> int | None: ...
    async def templates(self) -> list[Template]: ...
    async def webhooks(self) -> list[Webhook]: ...
    async def estimate_pruned_members(self, *, days: int, roles: list[Snowflake] = ...) -> int: ...
    async def invites(self) -> list[Invite]: ...
    async def create_template(self, *, name: str, description: str = ...) -> Template: ...
    async def create_integration(self, *, type: str, id: int) -> None: ...
    async def integrations(self) -> list[Integration]: ...
    async def fetch_stickers(self) -> list[GuildSticker]: ...
    async def fetch_sticker(self, sticker_id: int, /) -> GuildSticker: ...
    async def create_sticker(self, *, name: str, description: str | None = None, emoji: str, file: File, reason: str | None = None) -> GuildSticker: ...
    async def delete_sticker(self, sticker: Snowflake, *, reason: str | None = None) -> None: ...
    async def fetch_emojis(self) -> list[Emoji]: ...
    async def fetch_emoji(self, emoji_id: int, /) -> Emoji: ...
    async def create_custom_emoji(self, *, name: str, image: bytes, roles: list[Role] = ..., reason: str | None = None) -> Emoji: ...
    async def delete_emoji(self, emoji: Snowflake, *, reason: str | None = None) -> None: ...
    async def fetch_roles(self) -> list[Role]: ...
    @overload
    async def create_role(self, *, reason: str | None = ..., name: str = ..., permissions: Permissions = ..., colour: Colour | int = ..., hoist: bool = ..., mentionable: bool = ..., icon: bytes | None = ..., unicode_emoji: str | None = ...) -> Role: ...
    @overload
    async def create_role(self, *, reason: str | None = ..., name: str = ..., permissions: Permissions = ..., color: Colour | int = ..., hoist: bool = ..., mentionable: bool = ..., icon: bytes | None = ..., unicode_emoji: str | None = ...) -> Role: ...
    async def edit_role_positions(self, positions: dict[Snowflake, int], *, reason: str | None = None) -> list[Role]: ...
    async def kick(self, user: Snowflake, *, reason: str | None = None) -> None: ...
    async def ban(self, user: Snowflake, *, delete_message_seconds: int | None = None, reason: str | None = None) -> None: ...
    async def bulk_ban(self, *users: Snowflake, delete_message_seconds: int | None = None, reason: str | None = None) -> tuple[list[Snowflake], list[Snowflake]]: ...
    async def unban(self, user: Snowflake, *, reason: str | None = None) -> None: ...
    async def vanity_invite(self) -> Invite | None: ...
    def audit_logs(self, *, limit: int | None = 100, before: SnowflakeTime | None = None, after: SnowflakeTime | None = None, user: Snowflake = None, action: AuditLogAction = None) -> AuditLogIterator: ...
    async def widget(self) -> Widget: ...
    async def edit_widget(self, *, enabled: bool = ..., channel: Snowflake | None = ...) -> None: ...
    async def chunk(self, *, cache: bool = True) -> None: ...
    async def query_members(self, query: str | None = None, *, limit: int | None = 5, user_ids: list[int] | None = None, presences: bool = False, cache: bool = True) -> list[Member]: ...
    async def change_voice_state(self, *, channel: VocalGuildChannel | None, self_mute: bool = False, self_deaf: bool = False): ...
    async def welcome_screen(self): ...
    @overload
    async def edit_welcome_screen(self, *, description: str | None = ..., welcome_channels: list[WelcomeScreenChannel] | None = ..., enabled: bool | None = ...) -> WelcomeScreen: ...
    @overload
    async def edit_welcome_screen(self) -> None: ...
    async def fetch_scheduled_events(self, *, with_user_count: bool = True) -> list[ScheduledEvent]: ...
    async def fetch_scheduled_event(self, event_id: int, /, *, with_user_count: bool = True) -> ScheduledEvent | None: ...
    def get_scheduled_event(self, event_id: int, /) -> ScheduledEvent | None: ...
    async def create_scheduled_event(self, *, name: str, description: str = ..., start_time: datetime, end_time: datetime = ..., location: str | int | VoiceChannel | StageChannel | ScheduledEventLocation, privacy_level: ScheduledEventPrivacyLevel = ..., reason: str | None = None, image: bytes = ...) -> ScheduledEvent | None: ...
    @property
    def scheduled_events(self) -> list[ScheduledEvent]: ...
    async def fetch_auto_moderation_rules(self) -> list[AutoModRule]: ...
    async def fetch_auto_moderation_rule(self, id: int) -> AutoModRule: ...
    async def create_auto_moderation_rule(self, *, name: str, event_type: AutoModEventType, trigger_type: AutoModTriggerType, trigger_metadata: AutoModTriggerMetadata, actions: list[AutoModAction], enabled: bool = False, exempt_roles: list[Snowflake] = None, exempt_channels: list[Snowflake] = None, reason: str | None = None) -> AutoModRule: ...
    async def onboarding(self): ...
    async def edit_onboarding(self, *, prompts: list[OnboardingPrompt] | None = ..., default_channels: list[Snowflake] | None = ..., enabled: bool | None = ..., mode: OnboardingMode | None = ..., reason: str | None = ...) -> Onboarding: ...
    async def delete_auto_moderation_rule(self, id: int, *, reason: str | None = None) -> None: ...
    async def create_test_entitlement(self, sku: Snowflake) -> Entitlement: ...
    def entitlements(self, skus: list[Snowflake] | None = None, before: SnowflakeTime | None = None, after: SnowflakeTime | None = None, limit: int | None = 100, exclude_ended: bool = False) -> EntitlementIterator: ...
