import discord.abc
from .abc import Snowflake, SnowflakeTime
from .asset import Asset
from .channel import DMChannel
from .colour import Colour
from .flags import PublicUserFlags
from .guild import Guild
from .iterators import EntitlementIterator
from .message import Message
from .monetization import Entitlement
from .state import ConnectionState
from .types.user import PartialUser as PartialUserPayload, User as UserPayload
from datetime import datetime
from typing import Any, TypeVar

__all__ = ['User', 'ClientUser']

BU = TypeVar('BU', bound='BaseUser')

class _UserTag:
    id: int

class BaseUser(_UserTag):
    name: str
    id: int
    discriminator: str
    global_name: str | None
    bot: bool
    system: bool
    def __init__(self, *, state: ConnectionState, data: UserPayload | PartialUserPayload) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    @property
    def jump_url(self) -> str: ...
    @property
    def public_flags(self) -> PublicUserFlags: ...
    @property
    def avatar(self) -> Asset | None: ...
    @property
    def default_avatar(self) -> Asset: ...
    @property
    def display_avatar(self) -> Asset: ...
    @property
    def banner(self) -> Asset | None: ...
    @property
    def avatar_decoration(self) -> Asset | None: ...
    @property
    def accent_colour(self) -> Colour | None: ...
    @property
    def accent_color(self) -> Colour | None: ...
    @property
    def colour(self) -> Colour: ...
    @property
    def color(self) -> Colour: ...
    @property
    def mention(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
    @property
    def display_name(self) -> str: ...
    def mentioned_in(self, message: Message) -> bool: ...
    @property
    def is_migrated(self) -> bool: ...

class ClientUser(BaseUser):
    verified: bool
    locale: str | None
    mfa_enabled: bool
    def __init__(self, *, state: ConnectionState, data: UserPayload) -> None: ...
    async def edit(self, *, username: str = ..., avatar: bytes = ..., banner: bytes = ...) -> ClientUser: ...

class User(BaseUser, discord.abc.Messageable):
    def __init__(self, *, state: ConnectionState, data: UserPayload) -> None: ...
    def __del__(self) -> None: ...
    @property
    def dm_channel(self) -> DMChannel | None: ...
    @property
    def mutual_guilds(self) -> list[Guild]: ...
    async def create_dm(self) -> DMChannel: ...
    async def create_test_entitlement(self, sku: discord.abc.Snowflake) -> Entitlement: ...
    def entitlements(self, skus: list[Snowflake] | None = None, before: SnowflakeTime | None = None, after: SnowflakeTime | None = None, limit: int | None = 100, exclude_ended: bool = False) -> EntitlementIterator: ...
