from typing import Callable

__all__ = ['default_permissions', 'guild_only', 'is_nsfw']

def default_permissions(**perms: bool) -> Callable: ...
def guild_only() -> Callable: ...
def is_nsfw() -> Callable: ...
